"""
Django settings for minor project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
=======
Generated by 'django-admin startproject' using Django 3.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m3-v*i%mk#vb_c#@a4aux-81!ow1f9#l%(s$lddg^1ldmxa4_l'
=======
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x7&)r=g-v*^5#75_2j+2lf0v_sg1s+1!i_o)ccwh*q16h__+$k'
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'website',
]
=======
]

>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': ['website'],
=======
        'DIRS': [],
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
<<<<<<< HEAD
                'django.template.context_processors.media',
=======
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
            ],
        },
    },
]

WSGI_APPLICATION = 'minor.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
=======
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.1/topics/i18n/
=======
# https://docs.djangoproject.com/en/3.2/topics/i18n/
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

<<<<<<< HEAD
=======
USE_L10N = True

>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field



STATIC_URL = '/static/'

MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'

MESSAGE_TAGS={
        messages.ERROR: 'danger'
}

=======
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> 86824304de2580eeee05b3472a6bea444bc535d1
